version: '3'

services: 
  app: 
    build: .
    command: yarn start
    ports: 
      - '8080:8080'
    volumes: 
      - .:/usr/app
    networks: 
      - mysqlnetwork

  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    #command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cspdesafio
      - TZ=America/Sao_Paulo
    networks: 
      - mysqlnetwork
    volumes:
      - ./mysql/dbdata:/var/lib/mysql

networks:
  mysqlnetwork:
    driver: bridge